sudo: required
services:
  - docker

before_install:
  - docker build -t sameerapl18/react-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true sameerapl18/react-docker npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-967044410042"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $access_key
  secret_access_key: $secret_key
